# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    tags:
      - '[1-9]*.[0-9]*.[0-9]*'
jobs:
  schematic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Kibot
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: clock.kibot.yaml
          dir: output
          schema: clock.kicad_sch
          board: clock.kicad_pcb

  # schematic:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Generate PDF
  #       uses: emilymclean/kicad-pdf@v1
  #       with:
  #         input-files: clock.kicad_sch, clock.kicad_pcb
  #         output-file: clock.pdf

  #     # - name: Set up Kicad
  #     #   uses: actions-for-kicad/setup-kicad@v1
  #     #   with:
  #     #     version: "8.0"

  #     # - name: Generate PDF
  #     #   uses: actions-for-kicad/generate-kicad-files@v1
  #     #   with:
  #     #     file: ./clock.kicad_sch, ./clock.kicad_pcb]
  #     #     type: "schematic_pdf"
  #     #     black-and-white: false


      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SCHEMATIC
          #path: "./clock.pdf"
          path: ./output/*

  pcb:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Generate Images
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "./clock.kicad_pcb"
          output_path: "./images/"
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PCB
          path: "./images/"

      
  release-artifacts:
    permissions:
      contents: write
    needs:
      - schematic
      - pcb
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          #tag: "test"
          #tag: ${{ env.TAG }}
          tag: ${{ github.ref_name }}
          artifacts: "artifacts/*"
          prerelease: false
          body: "pdfs for a push"