# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"
      - uses: actions-for-kicad/generate-kicad-files@v1
        with:
          file: "./clock.kicad_sch"
          type: "schematic_pdf"
          black-and-white: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "clock.pdf"
          path: "./clock.pdf"