# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: emilymclean/kicad-pdf@v1
      with:
        input-files: clock.kicad_sch
        output-file: clock.pdf