# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-for-kicad/setup-kicad@v1
        with:
          version: "8.0"
      - uses: actions-for-kicad/generate-kicad-files@v1
        with:
          file: "./clock.kicad_sch"
          type: "schematic_pdf"
          black-and-white: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: "./clock.pdf"
  release-artifacts:
    permissions:
      contents: write
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: artifacts/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          #tag: "test"
          #tag: ${{ env.TAG }}
          tag: ${{ github.ref_name }}
          artifacts: "artifacts/*.pdf"
          prerelease: false
          body: "pdfs for a push"